Simplest support of Windows with Docker
maoe/viewprof pull request #5
Opened 2017-04-26 13:59 UTC by igrep

May fix #1 
But there're still problems:
- Requires `cygpath` (tool to convert Windows path into the POSIX one)
- Can't handle multiple arguments and options. (Is that really necessary for this tool?)

2017-04-27 20:54 UTC, maoe commented
Thanks for your contribution! Could you extend the README to show how to use it?

2017-05-07 21:01 UTC, maoe requested changes
Thanks! I've commented a few places.

2017-05-07 21:01 UTC, maoe commented on README.md
> +$ .\viewprof.bat path/to/file.prof
Does Windows accept forward slash delimiters?

2017-05-07 21:01 UTC, maoe commented on README.md
> +```bash
Should we use `bat` or something instead?

2017-05-07 21:01 UTC, maoe commented on README.md
> +$ git clone git@github.com:maoe/viewprof.git
Please drop the $-signs to make the instructions copy-paste friendly.

2017-05-07 21:01 UTC, maoe commented on README.md
> +For Windows users, see below.
Let's drop this sentence. The following instruction is short.

2017-05-07 23:49 UTC, igrep commented on README.md
> +$ .\viewprof.bat path/to/file.prof
Yes, actually whichever will do.

2017-05-08 00:13 UTC, maoe commented on README.md
> +$ .\viewprof.bat path/to/file.prof
That's good to know.

2017-05-08 00:14 UTC, maoe approved these changes
LGTM, thanks!

2017-05-08 00:20 UTC, maoe commented
Squashed last three commits and merged into feature/docker.

2017-05-08 00:20 UTC, closed without merging